import { QuizQuestion } from '../services/geminiService';

/**
 * デフォルト穴埋めクイズ問題（20問）
 * 履歴から5問揃わない場合にランダム補填で使用
 */
export const DEFAULT_QUIZ_QUESTIONS: QuizQuestion[] = [
  // 1. ชอบ（好き）
  {
    sentence_id: 'default_1',
    thai_text: 'ฉันชอบกินข้าวผัด',
    blank_text: 'ฉัน___กินข้าวผัด',
    correct_answer: 'ชอบ',
    choices: ['ชอบ', 'ไม่', 'จะ', 'ได้'],
    pronunciation: 'chôop',
    explanation: '「好き」を意味する動詞。ฉัน(私)＋ชอบ(好き)＋กิน(食べる)＋ข้าวผัด(チャーハン)',
    srs_interval: 0,
    japanese_translation: '私はチャーハンを食べるのが好きです',
    sentence_pronunciation: 'chǎn chôop kin khâao phàt',
  },
  // 2. อากาศ（天気）
  {
    sentence_id: 'default_2',
    thai_text: 'วันนี้อากาศร้อนมาก',
    blank_text: 'วันนี้___ร้อนมาก',
    correct_answer: 'อากาศ',
    choices: ['อากาศ', 'อาหาร', 'อาคาร', 'อายุ'],
    pronunciation: 'aa-kàat',
    explanation: '「天気」を意味する名詞。วันนี้(今日)＋อากาศ(天気)＋ร้อน(暑い)＋มาก(とても)',
    srs_interval: 0,
    japanese_translation: '今日はとても暑いです',
    sentence_pronunciation: 'wan-níi aa-kàat ráwn mâak',
  },
  // 3. โรงเรียน（学校）
  {
    sentence_id: 'default_3',
    thai_text: 'เขาไปโรงเรียนทุกวัน',
    blank_text: 'เขาไป___ทุกวัน',
    correct_answer: 'โรงเรียน',
    choices: ['โรงเรียน', 'โรงแรม', 'โรงพยาบาล', 'โรงหนัง'],
    pronunciation: 'roong-rian',
    explanation: '「学校」を意味する名詞。โรง(建物)系の選択肢で紛らわしいが、ทุกวัน(毎日)通うのは学校',
    srs_interval: 0,
    japanese_translation: '彼は毎日学校に行きます',
    sentence_pronunciation: 'khǎo pai roong-rian thúk wan',
  },
  // 4. น้ำส้ม（オレンジジュース）
  {
    sentence_id: 'default_4',
    thai_text: 'น้ำส้มอร่อยมาก',
    blank_text: '___อร่อยมาก',
    correct_answer: 'น้ำส้ม',
    choices: ['น้ำส้ม', 'น้ำตา', 'น้ำแข็ง', 'น้ำใจ'],
    pronunciation: 'nám-sôm',
    explanation: '「オレンジジュース」を意味する。อร่อย(美味しい)と組み合わさる飲み物',
    srs_interval: 0,
    japanese_translation: 'オレンジジュースがとても美味しいです',
    sentence_pronunciation: 'nám-sôm a-ròi mâak',
  },
  // 5. อาหาร（料理）
  {
    sentence_id: 'default_5',
    thai_text: 'แม่ทำอาหารที่บ้าน',
    blank_text: 'แม่ทำ___ที่บ้าน',
    correct_answer: 'อาหาร',
    choices: ['อาหาร', 'อากาศ', 'การบ้าน', 'อาชีพ'],
    pronunciation: 'aa-hǎan',
    explanation: '「料理・食べ物」を意味する名詞。แม่(母)がบ้าน(家)でทำ(作る)ものは料理',
    srs_interval: 0,
    japanese_translation: '母は家で料理を作ります',
    sentence_pronunciation: 'mâe tham aa-hǎan thîi bâan',
  },
  // 6. สวัสดี（こんにちは）
  {
    sentence_id: 'default_6',
    thai_text: 'สวัสดีครับผมชื่อสมชาย',
    blank_text: '___ครับผมชื่อสมชาย',
    correct_answer: 'สวัสดี',
    choices: ['สวัสดี', 'ขอบคุณ', 'ขอโทษ', 'ลาก่อน'],
    pronunciation: 'sa-wàt-dii',
    explanation: '「こんにちは」の挨拶。自己紹介の冒頭で使う定番表現',
    srs_interval: 0,
    japanese_translation: 'こんにちは、私の名前はソムチャイです',
    sentence_pronunciation: 'sa-wàt-dii khráp phǒm chûue sǒm-chaai',
  },
  // 7. ตลาด（市場）
  {
    sentence_id: 'default_7',
    thai_text: 'ฉันไปซื้อของที่ตลาด',
    blank_text: 'ฉันไปซื้อของที่___',
    correct_answer: 'ตลาด',
    choices: ['ตลาด', 'โรงแรม', 'สนามบิน', 'วัด'],
    pronunciation: 'ta-làat',
    explanation: '「市場」を意味する名詞。ซื้อของ(買い物)する場所として最も自然',
    srs_interval: 0,
    japanese_translation: '私は市場に買い物に行きます',
    sentence_pronunciation: 'chǎn pai súue khǎwng thîi ta-làat',
  },
  // 8. รถไฟ（電車）
  {
    sentence_id: 'default_8',
    thai_text: 'เราจะนั่งรถไฟไปเชียงใหม่',
    blank_text: 'เราจะนั่ง___ไปเชียงใหม่',
    correct_answer: 'รถไฟ',
    choices: ['รถไฟ', 'รถเมล์', 'รถยนต์', 'รถจักรยาน'],
    pronunciation: 'rót-fai',
    explanation: '「電車」を意味する名詞。เชียงใหม่への長距離移動に使う乗り物',
    srs_interval: 0,
    japanese_translation: '私たちは電車でチェンマイに行きます',
    sentence_pronunciation: 'rao jà nâng rót-fai pai chiang-mài',
  },
  // 9. เรียน（勉強する）
  {
    sentence_id: 'default_9',
    thai_text: 'น้องสาวเรียนภาษาไทย',
    blank_text: 'น้องสาว___ภาษาไทย',
    correct_answer: 'เรียน',
    choices: ['เรียน', 'สอน', 'อ่าน', 'เขียน'],
    pronunciation: 'rian',
    explanation: '「勉強する」を意味する動詞。ภาษาไทย(タイ語)を学ぶ動作',
    srs_interval: 0,
    japanese_translation: '妹はタイ語を勉強しています',
    sentence_pronunciation: 'náwng-sǎao rian phaa-sǎa thai',
  },
  // 10. แพง（高い/値段）
  {
    sentence_id: 'default_10',
    thai_text: 'กระเป๋านี้แพงเกินไป',
    blank_text: 'กระเป๋านี้___เกินไป',
    correct_answer: 'แพง',
    choices: ['แพง', 'ถูก', 'สวย', 'ใหญ่'],
    pronunciation: 'phaaeng',
    explanation: '「（値段が）高い」を意味する形容詞。เกินไป(〜すぎる)と組み合わせた不満の表現',
    srs_interval: 0,
    japanese_translation: 'このカバンは高すぎます',
    sentence_pronunciation: 'kra-pǎo níi phaaeng koen-pai',
  },
  // 11. หิว（お腹が空く）
  {
    sentence_id: 'default_11',
    thai_text: 'ฉันหิวข้าวมากเลย',
    blank_text: 'ฉัน___ข้าวมากเลย',
    correct_answer: 'หิว',
    choices: ['หิว', 'อิ่ม', 'กิน', 'ทำ'],
    pronunciation: 'hǐu',
    explanation: '「空腹である」を意味する。หิวข้าว(ご飯がお腹空いた)は日常的な表現',
    srs_interval: 0,
    japanese_translation: 'とてもお腹が空きました',
    sentence_pronunciation: 'chǎn hǐu khâao mâak loei',
  },
  // 12. สวย（美しい）
  {
    sentence_id: 'default_12',
    thai_text: 'ดอกไม้ในสวนสวยมาก',
    blank_text: 'ดอกไม้ในสวน___มาก',
    correct_answer: 'สวย',
    choices: ['สวย', 'เก่า', 'เล็ก', 'แพง'],
    pronunciation: 'sǔai',
    explanation: '「美しい」を意味する形容詞。ดอกไม้(花)を描写する自然な形容詞',
    srs_interval: 0,
    japanese_translation: '庭の花がとても美しいです',
    sentence_pronunciation: 'dàwk-mái nai sǔan sǔai mâak',
  },
  // 13. ทะเล（海）
  {
    sentence_id: 'default_13',
    thai_text: 'เด็กๆชอบเล่นที่ทะเล',
    blank_text: 'เด็กๆชอบเล่นที่___',
    correct_answer: 'ทะเล',
    choices: ['ทะเล', 'ภูเขา', 'แม่น้ำ', 'น้ำตก'],
    pronunciation: 'thá-lee',
    explanation: '「海」を意味する名詞。เด็กๆ(子供たち)がเล่น(遊ぶ)場所',
    srs_interval: 0,
    japanese_translation: '子供たちは海で遊ぶのが好きです',
    sentence_pronunciation: 'dèk-dèk chôop lên thîi thá-lee',
  },
  // 14. พูด（話す）
  {
    sentence_id: 'default_14',
    thai_text: 'คุณพูดภาษาไทยได้ไหม',
    blank_text: 'คุณ___ภาษาไทยได้ไหม',
    correct_answer: 'พูด',
    choices: ['พูด', 'ฟัง', 'เขียน', 'อ่าน'],
    pronunciation: 'phûut',
    explanation: '「話す」を意味する動詞。ภาษาไทย(タイ語)ができるか尋ねる定番フレーズ',
    srs_interval: 0,
    japanese_translation: 'タイ語を話せますか？',
    sentence_pronunciation: 'khun phûut phaa-sǎa thai dâai mǎi',
  },
  // 15. กาแฟ（コーヒー）
  {
    sentence_id: 'default_15',
    thai_text: 'ขอกาแฟเย็นหนึ่งแก้ว',
    blank_text: 'ขอ___เย็นหนึ่งแก้ว',
    correct_answer: 'กาแฟ',
    choices: ['กาแฟ', 'ชาเขียว', 'น้ำส้ม', 'นม'],
    pronunciation: 'kaa-faae',
    explanation: '「コーヒー」を意味する名詞。เย็น(冷たい)＋หนึ่งแก้ว(一杯)の注文表現',
    srs_interval: 0,
    japanese_translation: 'アイスコーヒーを一杯ください',
    sentence_pronunciation: 'khǎw kaa-faae yen nùeng kâaew',
  },
  // 16. นอน（寝る）
  {
    sentence_id: 'default_16',
    thai_text: 'เมื่อคืนผมนอนดึกมาก',
    blank_text: 'เมื่อคืนผม___ดึกมาก',
    correct_answer: 'นอน',
    choices: ['นอน', 'กิน', 'ทำงาน', 'ออกกำลังกาย'],
    pronunciation: 'nawn',
    explanation: '「寝る」を意味する動詞。นอนดึก(夜更かしする)は日常的な表現',
    srs_interval: 0,
    japanese_translation: '昨夜はとても遅くまで起きていました',
    sentence_pronunciation: 'mûea-khuuen phǒm nawn dùek mâak',
  },
  // 17. หมอ（医者）
  {
    sentence_id: 'default_17',
    thai_text: 'พี่ชายอยากเป็นหมอ',
    blank_text: 'พี่ชายอยากเป็น___',
    correct_answer: 'หมอ',
    choices: ['หมอ', 'ครู', 'ตำรวจ', 'ทหาร'],
    pronunciation: 'mǎw',
    explanation: '「医者」を意味する名詞。อยากเป็น(〜になりたい)＋職業名の構文',
    srs_interval: 0,
    japanese_translation: '兄は医者になりたいです',
    sentence_pronunciation: 'phîi-chaai yàak pen mǎw',
  },
  // 18. ฝน（雨）
  {
    sentence_id: 'default_18',
    thai_text: 'วันนี้ฝนตกหนักมาก',
    blank_text: 'วันนี้___ตกหนักมาก',
    correct_answer: 'ฝน',
    choices: ['ฝน', 'หิมะ', 'แดด', 'ลม'],
    pronunciation: 'fǒn',
    explanation: '「雨」を意味する名詞。ฝนตก(雨が降る)＋หนัก(激しい)は天気の定番表現',
    srs_interval: 0,
    japanese_translation: '今日は雨がとても激しく降っています',
    sentence_pronunciation: 'wan-níi fǒn tòk nàk mâak',
  },
  // 19. อร่อย（美味しい）
  {
    sentence_id: 'default_19',
    thai_text: 'ผัดไทยร้านนี้อร่อยที่สุด',
    blank_text: 'ผัดไทยร้านนี้___ที่สุด',
    correct_answer: 'อร่อย',
    choices: ['อร่อย', 'แพง', 'เผ็ด', 'ถูก'],
    pronunciation: 'a-ròi',
    explanation: '「美味しい」を意味する形容詞。ที่สุด(最も)と合わせた最上級表現',
    srs_interval: 0,
    japanese_translation: 'この店のパッタイが一番美味しいです',
    sentence_pronunciation: 'phàt-thai ráan níi a-ròi thîi-sùt',
  },
  // 20. ช้าง（象）
  {
    sentence_id: 'default_20',
    thai_text: 'เราไปดูช้างที่เชียงใหม่',
    blank_text: 'เราไปดู___ที่เชียงใหม่',
    correct_answer: 'ช้าง',
    choices: ['ช้าง', 'สิงโต', 'ลิง', 'เสือ'],
    pronunciation: 'cháang',
    explanation: '「象」を意味する名詞。เชียงใหม่で見る動物として最も有名',
    srs_interval: 0,
    japanese_translation: '私たちはチェンマイで象を見に行きます',
    sentence_pronunciation: 'rao pai duu cháang thîi chiang-mài',
  },
];
