project_id                    = "thai-memo-dev"
region                        = "asia-northeast1"
firebase_project_display_name = "Thai Memo Dev"
google_client_id              = "147810088545-4921rt150m9jtjate82nbol5q8hgoj3l.apps.googleusercontent.com"
apple_client_id               = "com.thaimemo.thaiMemo"
apple_team_id                 = "5KTT2C466P"
apple_key_id                  = "JGPGZZ5HRP"
