project_id                    = "thai-memo-prod"
region                        = "asia-northeast1"
firebase_project_display_name = "Thai Memo Prod"
google_client_id              = "219961294368-6lf7vceshitof77mflvjm0jujcbok68j.apps.googleusercontent.com" # TODO: GCP Console > APIs & Services > Credentials から取得
apple_client_id               = "com.thaimemo.thaiMemo"
apple_team_id                 = "5KTT2C466P"
apple_key_id                  = "JGPGZZ5HRP"
ci_service_account_email      = "github-actions-deployer@thai-memo-prod.iam.gserviceaccount.com"
github_repo                   = "mnbst/thai-memo"
