project_id                    = "thai-memo-67139"
region                        = "asia-northeast1"
gemini_api_key                = "AIzaSyAclzCd2WYwhpRhI_RTRPWLpL1hoJ4BtPA"
firebase_project_display_name = "Thai Memo (Tester)"
ci_service_account_email      = "github-actions-deployer@thai-memo-67139.iam.gserviceaccount.com"
