"""prompts.py のデータ部分を Go ソースへ書き出す。

システムプロンプトは組み立て済みの最終形を書き出す（テンプレート合成は
lang 以外の分岐が無いため、Go 側で組み立て直す必要がない）。
出力先: functions/go/internal/sentence/prompts_data.go

prompts.py のデータを変えたら必ず再実行すること:
    cd functions/python && uv run python scripts/gen_go/gen_prompts.py
"""

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

import prompts as p  # noqa: E402


def gs(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def slice_(name: str, doc: str, values) -> str:
    body = "".join(f"\t{gs(v)},\n" for v in values)
    return f"{doc}\nvar {name} = []string{{\n{body}}}\n\n"


def smap(name: str, doc: str, mapping: dict) -> str:
    body = "".join(f"\t{gs(k)}: {gs(v)},\n" for k, v in mapping.items())
    return f"{doc}\nvar {name} = map[string]string{{\n{body}}}\n\n"


def imap(name: str, doc: str, mapping: dict) -> str:
    body = "".join(f"\t{gs(k)}: {v},\n" for k, v in mapping.items())
    return f"{doc}\nvar {name} = map[string]int{{\n{body}}}\n\n"


def slice_map(name: str, doc: str, mapping: dict) -> str:
    parts = []
    for k, vs in mapping.items():
        inner = "".join(f"\t\t{gs(v)},\n" for v in vs)
        parts.append(f"\t{gs(k)}: {{\n{inner}\t}},\n")
    return f"{doc}\nvar {name} = map[string][]string{{\n" + "".join(parts) + "}\n\n"


def main() -> None:
    out = [
        "// Code generated by functions/python/scripts/gen_go/gen_prompts.py."
        " DO NOT EDIT.\n",
        "//\n",
        "// functions/python/prompts.py のデータ部分をそのまま写したもの。\n",
        "// システムプロンプトは組み立て済みの最終形。prompts.py 側の断片を\n",
        "// 変えたら再生成すること。\n",
        "\n",
        "package sentence\n\n",
        "import \"math\"\n\n",
    ]

    # --- システムプロンプト（組み立て済み） ---
    out.append(
        "// systemPrompts は tier × 言語ごとの固定システムプロンプト。\n"
        "// ja は毎回同じ文字列を返す（プロンプトキャッシュの prefix を壊さない）。\n"
        "var systemPrompts = map[string]map[string]string{\n"
    )
    for tier, ja, en in [
        ("premium", p.SYSTEM_PROMPT_PREMIUM, p._SYSTEM_PROMPTS_EN["premium"]),
        ("free", p.SYSTEM_PROMPT_FREE, p._SYSTEM_PROMPTS_EN["free"]),
    ]:
        out.append(f"\t{gs(tier)}: {{\n")
        out.append(f"\t\t\"ja\": {gs(ja)},\n")
        out.append(f"\t\t\"en\": {gs(en)},\n")
        out.append("\t},\n")
    out.append("}\n\n")

    # --- 難易度 ---
    out.append(
        "// DifficultyLevel は語彙帯ごとの難易度指定（prompts.DIFFICULTY_LEVELS）。\n"
        "//\n"
        "// Python の最上位帯は max_vocab が float(\"inf\") なので、Go では\n"
        "// math.MaxInt を使う（estimated_vocab がこれを超えることはない）。\n"
        "type DifficultyLevel struct {\n"
        "\tMaxVocab  int\n"
        "\tLabel     string\n"
        "\tVocabHint string\n"
        "}\n\n"
        "// difficultyLevels は max_vocab の昇順。\n"
        "var difficultyLevels = []DifficultyLevel{\n"
    )
    for lv in p.DIFFICULTY_LEVELS:
        max_vocab = lv["max_vocab"]
        go_max = "math.MaxInt" if max_vocab == float("inf") else str(int(max_vocab))
        out.append(
            f"\t{{MaxVocab: {go_max}, Label: {gs(lv['label'])}, "
            f"VocabHint: {gs(lv['vocab_hint'])}}},\n"
        )
    out.append("}\n\n")

    # --- 長さヒント ---
    out.append(
        "// introLengthHint は入門帯（vocab < 100）の長さヒント。\n"
        "// (MinVocab, Hint) を降順で判定する。\n"
        "type introLengthHint struct {\n\tMinVocab int\n\tHint     string\n}\n\n"
        "var introLengthHints = []introLengthHint{\n"
    )
    for min_vocab, hint in p.INTRO_LENGTH_HINTS:
        out.append(f"\t{{MinVocab: {min_vocab}, Hint: {gs(hint)}}},\n")
    out.append("}\n\n")
    out.append(
        "// minLengthHintWords は長さヒントの上限が下回らない語数。\n"
        f"const minLengthHintWords = {p.MIN_LENGTH_HINT_WORDS}\n\n"
    )

    # --- ルール群 ---
    out.append(slice_(
        "alwaysRules",
        "// alwaysRules は premium の【最後に確認】に常時載せるルール。",
        p._ALWAYS_RULES,
    ))
    out.append(slice_(
        "spokenRegisterRules",
        "// spokenRegisterRules は話し言葉のレジスタ制約。",
        p._SPOKEN_REGISTER_RULES,
    ))
    out.append(slice_(
        "romanceTopicRules",
        "// romanceTopicRules は恋愛 / タイBLドラマのテーマにだけ足すルール。",
        p._ROMANCE_TOPIC_RULES,
    ))
    out.append(slice_(
        "freeAlwaysRules",
        "// freeAlwaysRules は free の【最後に確認】に載せるルール。\n"
        "// premium の alwaysRules をそのまま付けると口語レジスタまで入って\n"
        "// tier 差が消えるため、意図的に空のままにしている。\n"
        "// 足すときは「正しさ」に当たるものだけ。",
        p._FREE_ALWAYS_RULES,
    ))
    out.append(slice_map(
        "translationRegisterRules",
        "// translationRegisterRules は言語ごとの訳文レジスタ制約。",
        p._TRANSLATION_REGISTER_RULES,
    ))
    out.append(smap(
        "ruleBannedWords",
        "// ruleBannedWords はルールが禁止している語 → そのルールを見分ける印。\n"
        "// ターゲット語が禁止語と衝突する場合、そのルールを落とす。",
        p._RULE_BANNED_WORDS,
    ))
    out.append(smap(
        "translationSteps",
        "// translationSteps は言語ごとの訳文の手順（末尾配置で効く）。",
        p.TRANSLATION_STEPS,
    ))

    # --- 関係（話し手と聞き手） ---
    out.append(slice_(
        "relationStatuses",
        "// relationStatuses は話し手から見た相手の地位。",
        p.RELATION_STATUSES,
    ))
    out.append(slice_(
        "relationIntimacy",
        "// relationIntimacy は話し手と聞き手の親密度。",
        p.RELATION_INTIMACY,
    ))
    out.append(
        "// relationBlock は【話し手と聞き手】ブロックのひな形。\n"
        "// {status} と {intimacy} を差し替える。\n"
        f"const relationBlock = {gs(p._RELATION_BLOCK)}\n\n"
    )
    out.append(
        "// functionWordSteps は機能語がターゲットのときに末尾へ足す手順。\n"
        f"const functionWordSteps = {gs(p.FUNCTION_WORD_STEPS)}\n\n"
    )

    # --- テーマのゲートとサブテーマ ---
    out.append(imap(
        "topicMinVocab",
        "// topicMinVocab はテーマごとの最低語彙。これ未満のユーザーには出さない。",
        p.TOPIC_MIN_VOCAB,
    ))
    out.append(slice_map(
        "topicSubThemes",
        "// topicSubThemes はテーマごとのサブテーマ候補。",
        p.TOPIC_SUB_THEMES,
    ))

    dest = os.path.abspath(os.path.join(
        os.path.dirname(__file__), "..", "..", "..",
        "go", "internal", "sentence", "prompts_data.go"))
    with open(dest, "w") as f:
        f.write("".join(out))
    print(f"wrote {dest}", file=sys.stderr)


main()
