"""constants.py のデータ部分を Go ソースへ書き出す。

手写しによる転記ミスを避けるため、Python の値をそのまま Go のリテラルにする。
出力先: functions/go/internal/sentence/constants_data.go

constants.py のデータを変えたら必ず再実行すること:
    cd functions/python && uv run python scripts/gen_go/gen_constants.py
"""

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

import constants as c  # noqa: E402


def go_string(s: str) -> str:
    """Go の文字列リテラル。JSON のエスケープ規則は Go とほぼ同じ。"""
    return json.dumps(s, ensure_ascii=False)


def go_string_slice(name: str, doc: str, values: list[str]) -> str:
    body = "".join(f"\t{go_string(v)},\n" for v in values)
    return f"{doc}\nvar {name} = []string{{\n{body}}}\n\n"


def go_string_map(name: str, doc: str, mapping: dict) -> str:
    body = "".join(
        f"\t{go_string(k)}: {go_string(v)},\n" for k, v in mapping.items()
    )
    return f"{doc}\nvar {name} = map[string]string{{\n{body}}}\n\n"


def go_nested_map(name: str, doc: str, mapping: dict) -> str:
    parts = []
    for outer, inner in mapping.items():
        inner_body = "".join(
            f"\t\t{go_string(k)}: {go_string(v)},\n" for k, v in inner.items()
        )
        parts.append(f"\t{go_string(outer)}: {{\n{inner_body}\t}},\n")
    return (
        f"{doc}\nvar {name} = map[string]map[string]string{{\n"
        + "".join(parts)
        + "}\n\n"
    )


def go_slice_map(name: str, doc: str, mapping: dict) -> str:
    parts = []
    for k, values in mapping.items():
        body = "".join(f"\t\t{go_string(v)},\n" for v in values)
        parts.append(f"\t{go_string(k)}: {{\n{body}\t}},\n")
    return (
        f"{doc}\nvar {name} = map[string][]string{{\n" + "".join(parts) + "}\n\n"
    )


def main() -> None:
    out = [
        "// Code generated by functions/python/scripts/gen_go/gen_constants.py."
        " DO NOT EDIT.\n",
        "//\n",
        "// functions/python/constants.py のデータ部分をそのまま写したもの。\n",
        "// constants.py 側を変えたら再生成すること。\n",
        "\n",
        "package sentence\n\n",
    ]

    out.append(go_string_slice(
        "Styles",
        "// Styles は生成する例文の文体バリエーション（constants.STYLES）。",
        c.STYLES,
    ))
    out.append(go_string_slice(
        "Topics",
        "// Topics は例文のテーマ（constants.TOPICS）。",
        c.TOPICS,
    ))
    out.append(go_string_slice(
        "GrammarFocuses",
        "// GrammarFocuses は文法の焦点（constants.GRAMMAR_FOCUSES）。",
        c.GRAMMAR_FOCUSES,
    ))
    out.append(go_string_slice(
        "TimeFrames",
        "// TimeFrames は時制の枠（constants.TIME_FRAMES）。",
        c.TIME_FRAMES,
    ))

    out.append(go_string_map(
        "topicLabelsEN",
        "// topicLabelsEN はテーマの英語ラベル（constants.TOPIC_LABELS_EN）。",
        c.TOPIC_LABELS_EN,
    ))
    out.append(go_string_map(
        "styleLabelsEN",
        "// styleLabelsEN は文体の英語ラベル（constants.STYLE_LABELS_EN）。",
        c.STYLE_LABELS_EN,
    ))
    out.append(go_string_map(
        "timeFrameLabelsEN",
        "// timeFrameLabelsEN は時制の英語ラベル（constants.TIME_FRAME_LABELS_EN）。",
        c.TIME_FRAME_LABELS_EN,
    ))
    out.append(go_nested_map(
        "subThemeLabelsEN",
        "// subThemeLabelsEN はサブテーマの英語ラベル（constants.SUB_THEME_LABELS_EN）。\n"
        "// 外側のキーはテーマ。",
        c.SUB_THEME_LABELS_EN,
    ))

    out.append(go_slice_map(
        "InterviewGoalTopics",
        "// InterviewGoalTopics はヒアリングの goal ごとのテーマ候補\n"
        "// （constants.INTERVIEW_GOAL_TOPICS）。値は TOPICS の要素。",
        c.INTERVIEW_GOAL_TOPICS,
    ))

    # BL_TOPIC は TOPICS[15] を参照している。インデックスではなく値で持つ。
    out.append(
        "// BLTopic は BL ドラマ回のテーマ（constants.BL_TOPIC = TOPICS[15]）。\n"
        f"const BLTopic = {go_string(c.BL_TOPIC)}\n\n"
    )
    out.append(
        "// FreeBLTopicRate は free ティアで BL テーマを引く確率\n"
        "// （constants.FREE_BL_TOPIC_RATE）。\n"
        f"const FreeBLTopicRate = {c.FREE_BL_TOPIC_RATE}\n\n"
    )

    # レスポンススキーマは構造が深いので JSON のまま埋め込む。
    out.append(
        "// responseJSONSchemaJSON は constants.RESPONSE_JSON_SCHEMA。\n"
        "// 構造が深いので JSON のまま持ち、必要なときにデコードして組み立てる。\n"
        "const responseJSONSchemaJSON = `"
        + json.dumps(c.RESPONSE_JSON_SCHEMA, ensure_ascii=False)
        + "`\n\n"
    )
    out.append(
        "// contextGeneratableFieldsJSON は constants._CONTEXT_GENERATABLE_FIELDS。\n"
        "const contextGeneratableFieldsJSON = `"
        + json.dumps(c._CONTEXT_GENERATABLE_FIELDS, ensure_ascii=False)
        + "`\n\n"
    )
    out.append(go_string_map(
        "schemaDescriptionsEN",
        "// schemaDescriptionsEN は constants._SCHEMA_DESCRIPTIONS_EN。",
        c._SCHEMA_DESCRIPTIONS_EN,
    ))
    out.append(go_string_map(
        "contextDescriptionsEN",
        "// contextDescriptionsEN は constants._CONTEXT_DESCRIPTIONS_EN。",
        c._CONTEXT_DESCRIPTIONS_EN,
    ))

    dest = os.path.join(
        os.path.dirname(__file__), "..", "..", "..",
        "go", "internal", "sentence", "constants_data.go",
    )
    dest = os.path.abspath(dest)
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    with open(dest, "w") as f:
        f.write("".join(out))
    print(f"wrote {dest}", file=sys.stderr)


main()
