"""word_classes.json を Go ソースへ書き出す。

出力先: functions/go/internal/wordclass/classes_data.go

word_classes.json を変えたら必ず再実行すること:
    cd functions/python && uv run python scripts/gen_go/gen_wordclasses.py
"""

import json
import os
import sys

HERE = os.path.dirname(__file__)


def go_string(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def main() -> None:
    path = os.path.join(HERE, "..", "..", "word_classes.json")
    with open(path, encoding="utf-8") as f:
        classes = json.load(f)["classes"]

    out = [
        "// Code generated by functions/python/scripts/gen_go/gen_wordclasses.py."
        " DO NOT EDIT.\n",
        "//\n",
        "// functions/python/word_classes.json をそのまま写したもの。\n",
        "// JSON 側を変えたら再生成すること。\n",
        "\n",
        "package wordclass\n\n",
        "// classOrder は JSON の定義順。同じ語が複数クラスに現れた場合は\n",
        "// 先に定義したクラスを採用するため、順序に意味がある。\n",
        "var classOrder = []string{\n",
    ]
    for cid in classes:
        out.append(f"\t{go_string(cid)},\n")
    out.append("}\n\n")

    out.append("// classes はクラスIDから定義への表。\n")
    out.append("var classes = map[string]Class{\n")
    for cid, c in classes.items():
        words = "".join(f"\t\t\t{go_string(w)},\n" for w in c["words"])
        out.append(f"\t{go_string(cid)}: {{\n")
        out.append(f"\t\tLabel: {go_string(c['label'])},\n")
        out.append(f"\t\tFunctionWord: {str(bool(c.get('function_word'))).lower()},\n")
        rule = c.get("rule") or ""
        out.append(f"\t\tRule: {go_string(rule)},\n")
        out.append(f"\t\tWords: []string{{\n{words}\t\t}},\n")
        out.append("\t},\n")
    out.append("}\n")

    dest = os.path.abspath(os.path.join(
        HERE, "..", "..", "..", "go", "internal", "wordclass", "classes_data.go"))
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    with open(dest, "w") as f:
        f.write("".join(out))
    print(f"wrote {dest} ({len(classes)} classes)", file=sys.stderr)


main()
