"""themes/bl_drama.py のデータ部分を Go ソースへ書き出す。

出力先: functions/go/internal/bldrama/data.go

bl_drama.py のデータを変えたら必ず再実行すること:
    cd functions/python && uv run python scripts/gen_go/gen_bldrama.py
"""

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from themes import bl_drama as bd  # noqa: E402


def gs(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def main() -> None:
    lines = [
        "// Code generated by scripts/gen_go/gen_bldrama.py. DO NOT EDIT.",
        "// 元データ: functions/python/themes/bl_drama.py",
        "",
        "package bldrama",
        "",
        "// shots はショットID → タイ語のセリフ。",
        "var shots = map[string]string{",
    ]
    for sid, text in bd.BL_DRAMA_SHOTS.items():
        lines.append(f"\t{gs(sid)}: {gs(text)},")
    lines += [
        "}",
        "",
        "// shotContext はショットID → 所属するドラマ設定・シーン名の逆引き。",
        "// セリフ単位で選出するため、選ばれたショットからドラマ設定を復元する。",
        "var shotContext = map[string]ShotContext{",
    ]
    for sid, ctx in bd._SHOT_CONTEXT.items():
        lines.append(
            f"\t{gs(sid)}: {{Drama: {gs(ctx['drama'])}, "
            f"Context: {gs(ctx['context'])}, Scene: {gs(ctx['scene'])}}},"
        )
    lines += [
        "}",
        "",
        "// shotIDs は shotContext のキーを Python の dict と同じ順で並べたもの。",
        "// ランダム選出のフォールバックが同じ候補集合を見るようにするため、",
        "// Go の map の走査順に頼らず順序を固定する。",
        "var shotIDs = []string{",
    ]
    for sid in bd._SHOT_CONTEXT:
        lines.append(f"\t{gs(sid)},")
    lines.append("}")
    lines.append("")

    path = os.path.join(
        os.path.dirname(__file__), "..", "..", "..",
        "go", "internal", "bldrama", "data.go",
    )
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("wrote", os.path.normpath(path))
    print(f"  shots: {len(bd.BL_DRAMA_SHOTS)}  shotContext: {len(bd._SHOT_CONTEXT)}")


if __name__ == "__main__":
    main()
