#!/usr/bin/env python3
"""静的コーパスの grammatical_role から品詞辞書を作る。

クイズのダミー選択肢は「正解と違う品詞の語」を選ぶ（quiz_distractors.go）。
語を単体でタガーに渡すと品詞がぶれる（ตอนนี้→接続詞、ที่จะ→代名詞）ので、
実際の文の中で付いた品詞を集計して辞書にし、タガーより先に引く。

同じ語に複数の品詞が付いた場合は最頻のものを採り、それが8割に満たない語は
辞書に入れない（曖昧な語はタガーに任せる）。固有名詞は名詞に寄せる
（ダミー選定では区別する意味がない）。

    python3 scripts/build_pos_dict.py \
        --in scripts/corpus/corpus.jsonl \
        --out functions/go/quiz_posdict_data.go
"""

import argparse
import collections
import json
import os

MERGE = {"固有名詞": "名詞"}
DOMINANCE = 0.8

HEADER = """// Code generated by scripts/build_pos_dict.py. DO NOT EDIT.
//
// 静的コーパス（scripts/corpus/corpus.jsonl）の word_breakdown に付いている
// grammatical_role を語ごとに集計したもの。文脈の中で付いた品詞なので、
// 語単体をタガーに渡すより安定する。最頻の品詞が{dominance:.0%}に満たない語は
// 入れていない（曖昧な語はタガーに任せる）。
//
// 語数 {count}。コーパスを作り直したら再生成すること。

package function

// corpusPOS は語 → 品詞（日本語ラベル）。
var corpusPOS = map[string]string{{
"""


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--in", dest="src", default="scripts/corpus/corpus.jsonl")
    parser.add_argument("--out", default="functions/go/quiz_posdict_data.go")
    args = parser.parse_args()

    counts = collections.defaultdict(collections.Counter)
    with open(args.src, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            for word in json.loads(line).get("words") or []:
                role = (word.get("grammatical_role") or "").strip()
                if role:
                    counts[word["word"]][MERGE.get(role, role)] += 1

    table = {}
    ambiguous = 0
    for word, roles in counts.items():
        top, n = roles.most_common(1)[0]
        if n / sum(roles.values()) >= DOMINANCE:
            table[word] = top
        else:
            ambiguous += 1

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(HEADER.format(dominance=DOMINANCE, count=len(table)))
        for word in sorted(table):
            f.write(f'\t{json.dumps(word, ensure_ascii=False)}: '
                    f'{json.dumps(table[word], ensure_ascii=False)},\n')
        f.write("}\n")

    print(f"{args.out}  {len(table)}語（曖昧で除外 {ambiguous}語）")


if __name__ == "__main__":
    main()
