import '../../data/models/quiz_question.dart';

/// サーバーからクイズが届かない場合に使用するデフォルト問題（5問）
const defaultQuizQuestions = <QuizQuestion>[
  QuizQuestion(
    sentenceId: 'default_1',
    thaiText: 'ฉันชอบกินข้าวผัด',
    blankText: 'ฉัน___กินข้าวผัด',
    correctAnswer: 'ชอบ',
    choices: ['ชอบ', 'ไม่', 'จะ', 'ได้'],
    pronunciation: 'chôop',
    explanation: '「好き」を意味する動詞。ฉัน(私)＋ชอบ(好き)＋กิน(食べる)＋ข้าวผัด(チャーハン)',
    japaneseTranslation: '私はチャーハンを食べるのが好きです',
    sentencePronunciation: 'chǎn chôop kin khâao phàt',
  ),
  QuizQuestion(
    sentenceId: 'default_2',
    thaiText: 'วันนี้อากาศร้อนมาก',
    blankText: 'วันนี้___ร้อนมาก',
    correctAnswer: 'อากาศ',
    choices: ['อากาศ', 'อาหาร', 'อาคาร', 'อายุ'],
    pronunciation: 'aa-kàat',
    explanation: '「天気」を意味する名詞。วันนี้(今日)＋อากาศ(天気)＋ร้อน(暑い)＋มาก(とても)',
    japaneseTranslation: '今日はとても暑いです',
    sentencePronunciation: 'wan-níi aa-kàat ráwn mâak',
  ),
  QuizQuestion(
    sentenceId: 'default_3',
    thaiText: 'เขาไปโรงเรียนทุกวัน',
    blankText: 'เขาไป___ทุกวัน',
    correctAnswer: 'โรงเรียน',
    choices: ['โรงเรียน', 'โรงแรม', 'โรงพยาบาล', 'โรงหนัง'],
    pronunciation: 'roong-rian',
    explanation: '「学校」を意味する名詞。โรง(建物)系の選択肢で紛らわしいが、ทุกวัน(毎日)通うのは学校',
    japaneseTranslation: '彼は毎日学校に行きます',
    sentencePronunciation: 'khǎo pai roong-rian thúk wan',
  ),
  QuizQuestion(
    sentenceId: 'default_4',
    thaiText: 'น้ำส้มอร่อยมาก',
    blankText: '___อร่อยมาก',
    correctAnswer: 'น้ำส้ม',
    choices: ['น้ำส้ม', 'น้ำตา', 'น้ำแข็ง', 'น้ำใจ'],
    pronunciation: 'nám-sôm',
    explanation: '「オレンジジュース」を意味する。อร่อย(美味しい)と組み合わさる飲み物',
    japaneseTranslation: 'オレンジジュースがとても美味しいです',
    sentencePronunciation: 'nám-sôm a-ròi mâak',
  ),
  QuizQuestion(
    sentenceId: 'default_5',
    thaiText: 'แม่ทำอาหารที่บ้าน',
    blankText: 'แม่ทำ___ที่บ้าน',
    correctAnswer: 'อาหาร',
    choices: ['อาหาร', 'อากาศ', 'การบ้าน', 'อาชีพ'],
    pronunciation: 'aa-hǎan',
    explanation: '「料理・食べ物」を意味する名詞。แม่(母)がบ้าน(家)でทำ(作る)ものは料理',
    japaneseTranslation: '母は家で料理を作ります',
    sentencePronunciation: 'mâe tham aa-hǎan thîi bâan',
  ),
];
